default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shopabot_development

test:
  <<: *default
  database: shopabot_test

production:
  <<: *default
  database: shopabot_production
  username: shopabot
  password: <%= ENV['SHOPABOT_DATABASE_PASSWORD'] %>
